### ISSUE TITLE
申领math部分的翻译

### ISSUE THREAD

**Issue by jinwei233** [sadhen/texmacs-doc-zh#1]
如题

**Comment by da-liii** [comment]
反正现在master分支没有什么文件，你翻译好之后直接放在master分支提PR好了

**Comment by brynne8** [comment]
我翻译了数学公式manual没翻译的部分。不太清楚怎么投递。
https://github.com/AlexanderMisel/texmacs-doc-zh/blob/patch-1/man-math.zh.tm

PS：我翻译的时候不知道这个文档是嵌入其他几个文档做成的，就直接去翻译了。不知道有没有办法处理。

**Comment by da-liii** [comment]
没问题，我手动处理一下就可以了，非常感谢

**Comment by da-liii** [comment]
这个部分内容比较多，有些地方还有一些翻译的问题，我这周末会抽空处理一下

大体上，还是翻译得非常棒的

**Comment by brynne8** [comment]
了解。感谢后续处理。

希望更多东西能够通过配置文件自定义。今天改了个<code>\date</code>的中文就动到cpp了，见https://github.com/texmacs/texmacs/pull/38/commits/5c31c954ddd7da29f4b0552579b5990eb6c529b6 。希望能仅仅通过改scm文件就能解决。

还有之前网友提到的book环境下的chapter的中文显示成了
![default](https://user-images.githubusercontent.com/7542439/42763450-ade14fcc-8945-11e8-8987-9e3270da719d.png)
应该像CTeX一样写成“第一章”就对了（如果偷懒的话，可以先写成“第1章”）

**Comment by da-liii** [comment]
@AlexanderMisel  just reviewed your translations and submitted. Thanks.
