### ISSUE TITLE
man-configuration的问题

### ISSUE THREAD

**Issue by brynne8** [sadhen/texmacs-doc-zh#2]
我用的Windows版TeXmacs的v 1.99.6。系统是Win 7，使用[slowphil](https://github.com/slowphil/mingw-w64-texmacs)发布的版本。
我的这个帮助文档一打开就是源码，然后也切不回实时预览的状态。英文版的manual能正常打开。见图。
![default](https://user-images.githubusercontent.com/7542439/42730293-5928af1a-8824-11e8-8480-84743c8e98f5.png)

**Comment by da-liii** [comment]
感谢反馈，我这里也有类似的问题

**Comment by da-liii** [comment]
尴尬，应该是2016年提交的时候就有这个问题
